#!/usr/bin/env python3
"""Generate the M2.1 native PCB placement baseline using KiCad's GUI update flow."""
from pathlib import Path
import os
import subprocess
import time

ROOT = Path(__file__).resolve().parents[1]
SCH = ROOT / "hardware/C64RS232_M1.kicad_sch"
PCB = ROOT / "hardware/C64RS232.kicad_pcb"

if not SCH.is_file():
    raise SystemExit(f"missing schematic: {SCH}")

# KiCad 9.0.x kicad-cli has no create-from-schematic/update-PCB command.
# Drive Eeschema's normal Tools -> Update PCB from Schematic flow headlessly.
env = os.environ.copy()
env["DISPLAY"] = ":99"
xvfb = subprocess.Popen(["Xvfb", ":99", "-screen", "0", "1280x1024x24"])
try:
    time.sleep(1)
    eeschema = subprocess.Popen(["eeschema", str(SCH)], env=env)
    time.sleep(8)

    # F8 is KiCad's Update PCB from Schematic hotkey.
    subprocess.run(["xdotool", "search", "--name", "Schematic Editor", "windowactivate", "--sync", "key", "F8"], env=env, check=False)
    time.sleep(6)

    # Accept/update the PCB dialog, then save the board.
    subprocess.run(["xdotool", "key", "Return"], env=env, check=False)
    time.sleep(5)
    subprocess.run(["xdotool", "key", "Return"], env=env, check=False)
    time.sleep(4)
    subprocess.run(["xdotool", "key", "ctrl+s"], env=env, check=False)
    time.sleep(3)
    subprocess.run(["xdotool", "key", "alt+F4"], env=env, check=False)
    time.sleep(2)
    eeschema.terminate()
    try:
        eeschema.wait(timeout=5)
    except subprocess.TimeoutExpired:
        eeschema.kill()
finally:
    xvfb.terminate()
    try:
        xvfb.wait(timeout=5)
    except subprocess.TimeoutExpired:
        xvfb.kill()

if not PCB.is_file() or PCB.stat().st_size == 0:
    raise SystemExit("native PCB was not generated by KiCad Update PCB from Schematic")

print(f"M2.1 native PCB baseline generated: {PCB}")
